# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{seedsv}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adrian Cuadros"]
  s.date = %q{2011-03-11}
  s.description = %q{Seed your database with data from csv files with ease}
  s.email = %q{adrian@innku.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/seedsv.rb",
    "lib/seedsv/csv_seed.rb",
    "lib/seedsv/engine.rb",
    "lib/tasks/seedsv.rake",
    "seedsv.gemspec",
    "test/helper.rb",
    "test/test_seedssv.rb"
  ]
  s.homepage = %q{http://github.com/adriancuadros/seedsv}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Seed your database with data from csv files with ease}
  s.test_files = [
    "test/helper.rb",
    "test/test_seedssv.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<fastercsv>, ["~> 1.5.1"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<fastercsv>, ["~> 1.5.1"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<fastercsv>, ["~> 1.5.1"])
  end
end

